from langchain.agents import create_agent
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

from tools import web_search, scrape_web

from dotenv import load_dotenv

load_dotenv()


# LLM

llm = ChatGroq(
    model="llama-3.1-8b-instant",
    temperature=0,
    max_tokens=800
)



# SEARCH AGENT

def build_search_agent():

    return create_agent(
        model=llm,
        tools=[web_search]
    )



# SEARCH + READER AGENT

def build_search_reader_agent():

    return create_agent(
        model=llm,
        tools=[scrape_web]
    )



# WRITER PROMPT

WRITER_PROMPT = """
You are a professional Writer Agent.

Your task is to transform provided research into
a polished and structured research report.

Rules:
- Use markdown formatting
- Use headings and subheadings
- Use bullet points when necessary
- Keep explanations clear and concise
- Preserve factual accuracy
- Do not invent facts
- Use only the provided research
- Never mention internal agent workflow
"""


write_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        WRITER_PROMPT
    ),

    (
        "human",
        """
Topic:
{topic}

Research:
{research}

Write a detailed research report.
"""
    )
])


writer_chain = write_prompt | llm | StrOutputParser()


# CRITIC PROMPT

CRITIC_PROMPT = """
You are an expert Critic Agent.

Your responsibility is to review and improve
research reports generated by the Writer Agent.

Focus on:
- factual accuracy
- clarity
- readability
- completeness
- formatting
- logical flow
- conciseness

Instructions:
- Identify weaknesses clearly
- Suggest improvements
- Rewrite weak sections if needed
- Do not invent facts
- Do not perform external research

If the report is already strong,
say:

"The response is accurate, clear,
and well-structured."
"""


critic_prompt = ChatPromptTemplate.from_messages([

    (
        "system",
        CRITIC_PROMPT
    ),

    (
        "human",
        """
Evaluate the report below and review it strictly.

{report}
"""
    )
])


critic_chain = critic_prompt | llm | StrOutputParser()